#creating related field
print("replace:Returns a string where a specified value is replaced with a specified value")
s3 = "hello world"
print(s3)
print(s3.replace("hello","Bye"))
print(s3.replace("hello","helloooooo"))
print("_____________________")
print("capitalize:Converts the first character to upper case")
print(s3)
print(s3.capitalize())
print("___________________________")
print("upper:Converts a string into upper case")
print(s3)
print(s3.upper())
print("______________________")
print("Lower:Converts a string into lower case")
s4 = "HELLO WORLD"
print(s4)
print(s4.lower())
print("_______________________________")
print("center:Returns a centered string")
print(s4)
print(s4.center(20))
print("_______________________________")
print("ljust:Returns a left justified version of the string")
y = "python"
x = y.ljust(20)
print(x,"is best")
print("_______________________________")
print("rjust:Returns a right justified version of the string")
print(y)
print(y.rjust(20))
print("_______________________________")
print("zfill:Fills the string with a specified number of 0 values at the beginning")
print(y)
print(y.zfill(20))
print("_______________________________")
print("strip:Returns a trimmed version of the string")
s5 = "the world is best"
print(s5)
print(s5.strip("t"))
print("_______________________________")
print("lstrip:Returns a left trim version of the string")
print("rstrip:Returns a right trim version of the string")
print(s5)
print(s5.lstrip("t"))
print(s5.rstrip("t"))