print("join:Joins the elements of an iterable to the end of the string")
seq = ["Computer", "science","and","techniques"]
print(seq)
s = " ".join(seq)
print(s)
print("__________________________________________________________")
print("split:Splits the string at the specified separator, and returns a list")
txt = "apple#banana#cherry#orange"
print(txt)
print(txt.split("#",2))
print(txt.split("#",3))
print("__________________________________________________________")
print("splitlines:Splits the string at line breaks and returns a list")
print(txt)
print(txt.splitlines())
print("__________________________________________________________")
print("rsplit:Splits the string at the specified separator, and returns a list")
print(txt)
print(txt.rsplit("#",1))
print(txt.rsplit("#",2))
print("__________________________________________________________")
print("partition:Returns a tuple where the string is parted into three parts")
print(txt)
print(txt.partition("banana"))
print(txt.partition("cherry"))
